import type { Enrolement } from '~/types/tresor'

export const mockEnrolements: Enrolement[] = [
  { id: 'ENR-001', institution: 'Office Togolais des Recettes', typeInstitution: 'Régie financière', demandeur: 'Koffi Mensah', email: 'k.mensah@otr.tg', telephone: '+228 90 12 34 56', servicesDemandes: 5, statut: 'Approuvé', dateDemande: '01/08/2026', dateTraitement: '01/08/2026', motif: 'Mise en place du paiement numérique pour les recettes' },
  { id: 'ENR-002', institution: 'Port Autonome de Lomé', typeInstitution: 'Établissement public', demandeur: 'Dodji Folly', email: 'd.folly@pal.tg', telephone: '+228 91 23 45 67', servicesDemandes: 3, statut: 'Approuvé', dateDemande: '03/08/2026', dateTraitement: '03/08/2026', motif: 'Digitalisation des droits portuaires' },
  { id: 'ENR-003', institution: 'Caisse de Retraites du Togo', typeInstitution: 'Institution publique', demandeur: 'Yawa Kossi', email: 'y.kossi@crt.tg', telephone: '+228 92 34 56 78', servicesDemandes: 2, statut: 'Approuvé', dateDemande: '05/08/2026', dateTraitement: '05/08/2026', motif: 'Versement automatisé des pensions' },
  { id: 'ENR-004', institution: 'Direction Générale des Douanes', typeInstitution: 'Administration', demandeur: 'Komlan Agbo', email: 'k.agbo@dgt.tg', telephone: '+228 93 45 67 89', servicesDemandes: 2, statut: 'Approuvé', dateDemande: '07/08/2026', dateTraitement: '07/08/2026', motif: 'Paiement des salaires par voie numérique' },
  { id: 'ENR-005', institution: 'Ministère de la Fonction Publique', typeInstitution: 'Administration', demandeur: 'Afi Doe', email: 'a.doe@mfp.tg', telephone: '+228 94 56 78 90', servicesDemandes: 2, statut: 'En attente', dateDemande: '12/08/2026', dateTraitement: null, motif: 'Bourses universitaires et allocations' },
  { id: 'ENR-006', institution: 'Direction des Transports', typeInstitution: 'Administration', demandeur: 'Abra Sitsofi', email: 'a.sitsofi@dgda.tg', telephone: '+228 95 67 89 01', servicesDemandes: 2, statut: 'En attente', dateDemande: '15/08/2026', dateTraitement: null, motif: 'Paiement des permis de conduire et taxes routières' },
  { id: 'ENR-007', institution: 'Commune de Lomé', typeInstitution: 'Collectivité territoriale', demandeur: 'Suru Kpatar', email: 's.kpatar@lome.tg', telephone: '+228 96 78 90 12', servicesDemandes: 3, statut: 'Rejeté', dateDemande: '10/08/2026', dateTraitement: '14/08/2026', motif: 'Taxe foncière et patente' },
]
