import type { Institution } from '~/types/tresor'

export const mockInstitutions: Institution[] = [
  {
    id: 'otr',
    nom: 'Office Togolais des Recettes',
    type: 'Régie financière',
    nbServices: 5,
    nbAlias: 5,
    nbTransactions: 12540,
    statut: 'Active',
    dateEnrolement: '01/08/2026',
  },
  {
    id: 'pal',
    nom: 'Port Autonome de Lomé',
    type: 'Établissement public',
    nbServices: 3,
    nbAlias: 3,
    nbTransactions: 4230,
    statut: 'Active',
    dateEnrolement: '03/08/2026',
  },
  {
    id: 'crt',
    nom: 'Caisse de Retraites du Togo',
    type: 'Institution publique',
    nbServices: 2,
    nbAlias: 2,
    nbTransactions: 1840,
    statut: 'Active',
    dateEnrolement: '05/08/2026',
  },
  {
    id: 'dgt',
    nom: 'Direction Générale des Douanes',
    type: 'Administration',
    nbServices: 2,
    nbAlias: 2,
    nbTransactions: 3560,
    statut: 'Active',
    dateEnrolement: '07/08/2026',
  },
  {
    id: 'mfp',
    nom: 'Ministère de la Fonction Publique',
    type: 'Administration',
    nbServices: 2,
    nbAlias: 2,
    nbTransactions: 950,
    statut: 'En attente',
    dateEnrolement: '12/08/2026',
  },
  {
    id: 'dgda',
    nom: 'Direction des Transports',
    type: 'Administration',
    nbServices: 2,
    nbAlias: 2,
    nbTransactions: 680,
    statut: 'En attente',
    dateEnrolement: '15/08/2026',
  },
]
