import type { Service } from '~/types/tresor'

export const mockServices: Service[] = [
  { id: 's1', nom: 'Impôts', institution: 'Office Togolais des Recettes', institutionId: 'otr', type: 'Recette', description: 'Recouvrement des impôts directs et indirects', alias: 'OTR-IMPOTS', aliasId: 'a1', compte: 'TASC', statut: 'Actif', nbTransactions: 5240, dateCreation: '01/08/2026' },
  { id: 's2', nom: 'Douanes', institution: 'Office Togolais des Recettes', institutionId: 'otr', type: 'Recette', description: 'Perception des droits de douane', alias: 'OTR-DOUANES', aliasId: 'a2', compte: 'TASC', statut: 'Actif', nbTransactions: 3850, dateCreation: '01/08/2026' },
  { id: 's3', nom: 'Taxes', institution: 'Office Togolais des Recettes', institutionId: 'otr', type: 'Recette', description: 'Perception des taxes diverses', alias: 'OTR-TAXES', aliasId: 'a3', compte: 'TASC', statut: 'Actif', nbTransactions: 2100, dateCreation: '02/08/2026' },
  { id: 's4', nom: 'Amendes', institution: 'Office Togolais des Recettes', institutionId: 'otr', type: 'Recette', description: 'Recouvrement des amendes et pénalités', alias: 'OTR-AMENDES', aliasId: 'a4', compte: 'TASC', statut: 'Actif', nbTransactions: 1250, dateCreation: '02/08/2026' },
  { id: 's5', nom: 'Loyers domaniaux', institution: 'Port Autonome de Lomé', institutionId: 'pal', type: 'Recette', description: 'Perception des loyers sur les terrains domaniaux', alias: 'PAL-LOYERS', aliasId: null, compte: 'TASC', statut: 'Actif', nbTransactions: 980, dateCreation: '03/08/2026' },
  { id: 's6', nom: 'Droits portuaires', institution: 'Port Autonome de Lomé', institutionId: 'pal', type: 'Recette', description: 'Perception des droits de port et manutention', alias: 'PAL-DROITS', aliasId: 'a5', compte: 'TASC', statut: 'Actif', nbTransactions: 2850, dateCreation: '03/08/2026' },
  { id: 's7', nom: 'Stationnement', institution: 'Port Autonome de Lomé', institutionId: 'pal', type: 'Recette', description: 'Droits de stationnement des navires', alias: 'PAL-STATIONNEMENT', aliasId: null, compte: 'TASC', statut: 'Inactif', nbTransactions: 400, dateCreation: '03/08/2026' },
  { id: 's8', nom: 'Retraites', institution: 'Caisse de Retraites du Togo', institutionId: 'crt', type: 'Prestation', description: 'Versement des pensions de retraite', alias: 'CRT-RETRAITES', aliasId: 'a6', compte: 'TASC', statut: 'Actif', nbTransactions: 1840, dateCreation: '05/08/2026' },
  { id: 's9', nom: 'Salaires', institution: 'Direction Générale des Douanes', institutionId: 'dgt', type: 'Dépense', description: 'Versement des salaires des agents', alias: 'DGT-SALAIRES', aliasId: 'a7', compte: 'TASC', statut: 'Actif', nbTransactions: 2100, dateCreation: '07/08/2026' },
  { id: 's10', nom: 'Bourses', institution: 'Ministère de la Fonction Publique', institutionId: 'mfp', type: 'Prestation', description: 'Versement des bourses universitaires', alias: 'MFP-BOURSES', aliasId: null, compte: 'TASC', statut: 'En attente', nbTransactions: 350, dateCreation: '12/08/2026' },
]
