import type {
  ApiEndpoint,
  DocSection,
  MockApiKey,
  MockApp,
  MockLogEntry,
  MockStats,
} from '~/types/platform'

export const MOCK_STATS: MockStats = {
  totalRequests: 145230,
  successRate: 98.7,
  avgLatency: 142,
  activeApps: 3,
  requestsToday: 2847,
  errorsToday: 12,
}

export const MOCK_APPS: MockApp[] = [
  {
    id: 'app_001',
    name: 'Mobile Banking App',
    description: 'Application mobile de services bancaires pour les clients finaux.',
    status: 'active',
    createdAt: '2025-11-15',
    environment: 'sandbox',
    baseUrl: 'https://sandbox-api.tresor.bf/v1',
  },
  {
    id: 'app_002',
    name: 'API Partenaire Web',
    description: 'Intégration API pour les partenaires commerciaux e-commerce.',
    status: 'active',
    createdAt: '2026-01-20',
    environment: 'sandbox',
    baseUrl: 'https://sandbox-api.tresor.bf/v1',
  },
  {
    id: 'app_003',
    name: 'SMS Gateway Service',
    description: 'Service de notification par SMS pour les alertes de transactions.',
    status: 'inactive',
    createdAt: '2026-03-10',
    environment: 'sandbox',
    baseUrl: 'https://sandbox-api.tresor.bf/v1',
  },
]

export const MOCK_API_KEYS: MockApiKey[] = [
  {
    id: 'key_001',
    clientId: 'client_a1b2c3d4e5f6',
    secret: 'sk_live_xxxxxxxxxxxxxxxxxxxxxxxx',
    name: 'Production Key - Mobile App',
    appId: 'app_001',
    status: 'active',
    createdAt: '2025-12-01',
    expiresAt: '2026-12-01',
    lastUsedAt: '2026-08-17T14:32:00Z',
    permissions: ['comptes:read', 'transferts:write', 'operations:read'],
  },
  {
    id: 'key_002',
    clientId: 'client_g7h8i9j0k1l2',
    secret: 'sk_test_yyyyyyyyyyyyyyyyyyyyyyyy',
    name: 'Sandbox Key - Partenaire Web',
    appId: 'app_002',
    status: 'active',
    createdAt: '2026-02-15',
    expiresAt: '2027-02-15',
    lastUsedAt: '2026-08-17T09:15:00Z',
    permissions: ['comptes:read', 'operations:read'],
  },
  {
    id: 'key_003',
    clientId: 'client_m3n4o5p6q7r8',
    secret: 'sk_test_zzzzzzzzzzzzzzzzzzzzzzzz',
    name: 'Sandbox Key - SMS Gateway',
    appId: 'app_003',
    status: 'revoked',
    createdAt: '2026-04-01',
    expiresAt: '2027-04-01',
    lastUsedAt: null,
    permissions: ['notifications:write'],
  },
]

export const MOCK_LOGS: MockLogEntry[] = [
  { id: 'log_001', timestamp: '2026-08-18T10:32:15Z', method: 'GET', endpoint: '/v1/comptes/12345', statusCode: 200, latency: 89, clientId: 'client_a1b2c3d4e5f6', description: 'Consultation du solde du compte 12345' },
  { id: 'log_002', timestamp: '2026-08-18T10:31:42Z', method: 'POST', endpoint: '/v1/transferts', statusCode: 201, latency: 234, clientId: 'client_a1b2c3d4e5f6', description: 'Transfert de 25 000 FCFA initié' },
  { id: 'log_003', timestamp: '2026-08-18T10:30:18Z', method: 'GET', endpoint: '/v1/operations', statusCode: 200, latency: 156, clientId: 'client_g7h8i9j0k1l2', description: 'Liste des 50 dernières opérations' },
  { id: 'log_004', timestamp: '2026-08-18T10:29:55Z', method: 'POST', endpoint: '/v1/auth/token', statusCode: 200, latency: 67, clientId: 'client_a1b2c3d4e5f6', description: 'Obtention d\'un token d\'accès' },
  { id: 'log_005', timestamp: '2026-08-18T10:28:30Z', method: 'GET', endpoint: '/v1/comptes/99999', statusCode: 404, latency: 45, clientId: 'client_g7h8i9j0k1l2', description: 'Compte introuvable' },
  { id: 'log_006', timestamp: '2026-08-18T10:27:12Z', method: 'POST', endpoint: '/v1/transferts', statusCode: 400, latency: 78, clientId: 'client_a1b2c3d4e5f6', description: 'Solde insuffisant pour le transfert' },
  { id: 'log_007', timestamp: '2026-08-18T10:25:44Z', method: 'GET', endpoint: '/v1/comptes/12345', statusCode: 200, latency: 92, clientId: 'client_a1b2c3d4e5f6', description: 'Consultation du solde du compte 12345' },
  { id: 'log_008', timestamp: '2026-08-18T10:24:10Z', method: 'GET', endpoint: '/v1/operations/67890', statusCode: 200, latency: 110, clientId: 'client_g7h8i9j0k1l2', description: 'Détail de l\'opération 67890' },
  { id: 'log_009', timestamp: '2026-08-18T10:22:33Z', method: 'DELETE', endpoint: '/v1/transferts/11111', statusCode: 403, latency: 52, clientId: 'client_g7h8i9j0k1l2', description: 'Annulation non autorisée' },
  { id: 'log_010', timestamp: '2026-08-18T10:20:01Z', method: 'GET', endpoint: '/v1/comptes', statusCode: 200, latency: 198, clientId: 'client_a1b2c3d4e5f6', description: 'Liste des comptes de l\'utilisateur' },
]

export const MOCK_ENDPOINTS: ApiEndpoint[] = [
  {
    id: 'ep_001',
    method: 'POST',
    path: '/v1/auth/token',
    title: 'Obtenir un token d\'accès',
    description: 'Authentifie un développeur et retourne un token d\'accès JWT pour les appels API suivants.',
    category: 'Authentification',
    parameters: [],
    requestBody: {
      contentType: 'application/json',
      schema: '{\n  "client_id": "string",\n  "client_secret": "string",\n  "grant_type": "client_credentials"\n}',
      example: '{\n  "client_id": "client_a1b2c3d4e5f6",\n  "client_secret": "sk_live_xxx...",\n  "grant_type": "client_credentials"\n}',
    },
    responseExample: '{\n  "status": "success",\n  "data": {\n    "access_token": "eyJhbGciOiJIUzI1NiIs...",\n    "token_type": "Bearer",\n    "expires_in": 3600\n  }\n}',
    statusCode: 200,
  },
  {
    id: 'ep_002',
    method: 'GET',
    path: '/v1/comptes',
    title: 'Lister les comptes',
    description: 'Retourne la liste des comptes associés au client authentifié.',
    category: 'Comptes',
    parameters: [
      { name: 'page', type: 'integer', required: false, description: 'Numéro de page (défaut: 1)', example: '1' },
      { name: 'limit', type: 'integer', required: false, description: 'Nombre de résultats par page (défaut: 20, max: 100)', example: '20' },
      { name: 'statut', type: 'string', required: false, description: 'Filtrer par statut du compte (actif, bloque, ferme)', example: 'actif' },
    ],
    responseExample: '{\n  "status": "success",\n  "data": {\n    "comptes": [\n      {\n        "id": "12345",\n        "numero": "BF001 2345 6789 0123",\n        "titulaire": "Jean Dupont",\n        "solde": 150000.00,\n        "devise": "XOF",\n        "statut": "actif",\n        "date_creation": "2025-06-15"\n      }\n    ],\n    "pagination": {\n      "page": 1,\n      "limit": 20,\n      "total": 3\n    }\n  }\n}',
    statusCode: 200,
  },
  {
    id: 'ep_003',
    method: 'GET',
    path: '/v1/comptes/{id}',
    title: 'Détails d\'un compte',
    description: 'Retourne les informations détaillées d\'un compte spécifique par son identifiant.',
    category: 'Comptes',
    parameters: [
      { name: 'id', type: 'string', required: true, description: 'Identifiant unique du compte', example: '12345' },
    ],
    responseExample: '{\n  "status": "success",\n  "data": {\n    "id": "12345",\n    "numero": "BF001 2345 6789 0123",\n    "titulaire": "Jean Dupont",\n    "solde": 150000.00,\n    "devise": "XOF",\n    "statut": "actif",\n    "date_creation": "2025-06-15",\n    "iban": "BF00 1234 5678 9012 3456 7890",\n    "bic": "TRORBJBF"\n  }\n}',
    statusCode: 200,
  },
  {
    id: 'ep_004',
    method: 'POST',
    path: '/v1/transferts',
    title: 'Initier un transfert',
    description: 'Crée une nouvelle demande de transfert de fonds entre deux comptes.',
    category: 'Transferts',
    parameters: [],
    requestBody: {
      contentType: 'application/json',
      schema: '{\n  "compte_source": "string",\n  "compte_destination": "string",\n  "montant": number,\n  "devise": "string",\n  "motif": "string",\n  "reference_client": "string"\n}',
      example: '{\n  "compte_source": "12345",\n  "compte_destination": "67890",\n  "montant": 25000.00,\n  "devise": "XOF",\n  "motif": "Paiement facture",\n  "reference_client": "INV-2026-001"\n}',
    },
    responseExample: '{\n  "status": "success",\n  "data": {\n    "id": "tx_abc123",\n    "statut": "en_cours",\n    "compte_source": "12345",\n    "compte_destination": "67890",\n    "montant": 25000.00,\n    "devise": "XOF",\n    "date_initiation": "2026-08-18T10:30:00Z"\n  }\n}',
    statusCode: 201,
  },
  {
    id: 'ep_005',
    method: 'GET',
    path: '/v1/transferts/{id}',
    title: 'Statut d\'un transfert',
    description: 'Retourne le statut et les détails d\'un transfert identifié par son ID.',
    category: 'Transferts',
    parameters: [
      { name: 'id', type: 'string', required: true, description: 'Identifiant unique du transfert', example: 'tx_abc123' },
    ],
    responseExample: '{\n  "status": "success",\n  "data": {\n    "id": "tx_abc123",\n    "statut": "confirme",\n    "montant": 25000.00,\n    "devise": "XOF",\n    "date_initiation": "2026-08-18T10:30:00Z",\n    "date_confirmation": "2026-08-18T10:30:45Z",\n    "reference_client": "INV-2026-001"\n  }\n}',
    statusCode: 200,
  },
  {
    id: 'ep_006',
    method: 'GET',
    path: '/v1/operations',
    title: 'Historique des opérations',
    description: 'Retourne l\'historique des opérations financières avec filtrage et pagination.',
    category: 'Opérations',
    parameters: [
      { name: 'compte_id', type: 'string', required: true, description: 'Identifiant du compte', example: '12345' },
      { name: 'date_debut', type: 'string', required: false, description: 'Date de début (format ISO 8601)', example: '2026-08-01' },
      { name: 'date_fin', type: 'string', required: false, description: 'Date de fin (format ISO 8601)', example: '2026-08-18' },
      { name: 'type', type: 'string', required: false, description: 'Type d\'opération (credit, debit, virement)', example: 'debit' },
      { name: 'page', type: 'integer', required: false, description: 'Numéro de page', example: '1' },
      { name: 'limit', type: 'integer', required: false, description: 'Nombre de résultats', example: '50' },
    ],
    responseExample: '{\n  "status": "success",\n  "data": {\n    "operations": [\n      {\n        "id": "op_67890",\n        "type": "debit",\n        "montant": -5000.00,\n        "devise": "XOF",\n        "description": "Paiement facture EDF",\n        "date": "2026-08-17T16:45:00Z",\n        "solde_apres": 145000.00\n      }\n    ],\n    "pagination": {\n      "page": 1,\n      "limit": 50,\n      "total": 128\n    }\n  }\n}',
    statusCode: 200,
  },
  {
    id: 'ep_007',
    method: 'POST',
    path: '/v1/webhooks',
    title: 'Enregistrer un webhook',
    description: 'Enregistre une URL de callback pour recevoir des notifications en temps réel sur les événements.',
    category: 'Webhooks',
    parameters: [],
    requestBody: {
      contentType: 'application/json',
      schema: '{\n  "url": "string",\n  "events": ["string"],\n  "secret": "string"\n}',
      example: '{\n  "url": "https://mon-app.bf/webhook",\n  "events": ["transfert.confirme", "compte.modifie"],\n  "secret": "whsec_xxx..."\n}',
    },
    responseExample: '{\n  "status": "success",\n  "data": {\n    "id": "wh_001",\n    "url": "https://mon-app.bf/webhook",\n    "events": ["transfert.confirme", "compte.modifie"],\n    "actif": true,\n    "date_creation": "2026-08-18T10:00:00Z"\n  }\n}',
    statusCode: 201,
  },
]

export const DOC_SECTIONS: DocSection[] = [
  {
    id: 'introduction',
    title: 'Introduction',
    icon: 'i-lucide-book-open',
  },
  {
    id: 'authentication',
    title: 'Authentification',
    icon: 'i-lucide-shield',
  },
  {
    id: 'endpoints',
    title: 'Endpoints',
    icon: 'i-lucide-code',
    children: [
      { id: 'auth-token', title: 'Token d\'accès', icon: 'i-lucide-key' },
      { id: 'comptes', title: 'Comptes', icon: 'i-lucide-wallet' },
      { id: 'transferts', title: 'Transferts', icon: 'i-lucide-arrow-right-left' },
      { id: 'operations', title: 'Opérations', icon: 'i-lucide-scroll-text' },
      { id: 'webhooks', title: 'Webhooks', icon: 'i-lucide-bell' },
    ],
  },
  {
    id: 'schemas',
    title: 'Schémas de données',
    icon: 'i-lucide-database',
  },
  {
    id: 'errors',
    title: 'Gestion des erreurs',
    icon: 'i-lucide-alert-triangle',
  },
  {
    id: 'rate-limits',
    title: 'Limites de débit',
    icon: 'i-lucide-gauge',
  },
  {
    id: 'sdks',
    title: 'SDKs & Exemples',
    icon: 'i-lucide-package',
  },
  {
    id: 'changelog',
    title: 'Changelog',
    icon: 'i-lucide-file-text',
  },
]
